import Providers from "@/components/Providers";
import "./globals.css";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, popups }) {
  return (
    <html lang="ru">
      <body className="font-text bg-[#000000] text-white">
        <Providers>
          {children}
          {popups}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
