import Providers from "@/components/Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className="font-text text-[#000]">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
