import Providers from "@/components/Providers";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, popups }) {
  return (
    <html lang="ru">
      <body className="font-text text-[#000]">
        <Providers>
          {children}
          {popups}
        </Providers>
      </body>
    </html>
  );
}
